on:
  watch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/update.yml"

jobs:
  update:
    if: github.repository == 'ymcoming/caddy2-naiveproxy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.*' # The Go version to download (if necessary) and use.
      - run: |
            export PATH=${GOROOT}/bin:$PATH
            go version
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
            xcaddy build latest \
                --with github.com/mholt/caddy-l4 \
                --with github.com/caddy-dns/cloudflare \
                --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive
            tar -czvf caddy.tar.gz caddy
            rm -f caddy
            # push
            git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
            git commit -am "update"
            git push -v --progress
