name: build
on:
  schedule:
    - cron: "30 0 * * FRI"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: '^1.17.2'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build & Push
      run: |
        bash build.sh
